### PR TITLE
Add screenrecord argument

### PR DESCRIPTION
**Pull request by THouriezPEReN**
Adding optional new argument to disable screen recording.

### CODE REVIEW

**Comment by THouriezPEReN** [comment]
Hello, 

I made the change to instrument_single, i could extend the change to instrument_gated if you are OK with it.

**Comment by U039b** [comment]
Hi!
It's a very good idea. Don't hesitate to add the same parameter to the `priogue-instrument_gated`.

**Comment by U039b** [comment]
Thank you!

**Comment by U039b** [comment]
The version v1.1.2 will be available on the PPA in a few minutes. Thank you very much for your contribution!

**Pull request merged**
